### ISSUE TITLE
Incorrect LUMO energy extraction for some xyz files

### ISSUE THREAD

**Issue by HelloJocelynLu** [hkneiding/uxtbpy#3]
Hi,

Thank you for creating uxtbpy, which makes xtb calling accessible as a Python API! I recently encountered an issue with LUMO energy extraction for some xyz files. For example:

```
...
   *** convergence criteria satisfied after 16 iterations ***

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -0.8375023             -22.7896
       ...           ...                  ...                  ...
       104        2.0000           -0.3599362              -9.7944 (HOMO)
       105        0.0000           -0.3291062              -8.9554 (LUMO)
       106                         -0.2656783              -7.2295
       ...
       185                          1.6005732              43.5538
      -------------------------------------------------------------
                  HL-Gap            0.0308299 Eh            0.8389 eV
             Fermi-level           -0.3445198 Eh           -9.3749 eV
....
```
In the code:
https://github.com/hkneiding/uxtbpy/blob/8390296a3677abf19e2f6751cf36cb1bd465d035/uxtbpy/xtb_output_parser.py#L150-L158
the LUMO energy extraction looks for the "(LUMO)" keyword to retrieve the third element from `line_split`. In this case, it returns:
```
{'homo_energy': -9.7944, 'lumo_energy': -0.3291048, ...}
```
However, the LUMO energy is in Eh rather than eV. The issue arises with molecules that have a column with Occupation 0.0000, while most other cases work correctly.

For your reference, I’m attaching an example xyz file that causes the issue (remove .txt)
[mol.xyz.txt](https://github.com/user-attachments/files/17290421/mol.xyz.txt)

`xtb mol.xyz --opt tight --uhf 0 --norestart -v -c 0`

**Comment by hkneiding** [comment]
Hi,

thanks for bringing this to my attention!

It seems that the following line causes a problem for the parser:
`105        0.0000           -0.3291062              -8.9554 (LUMO)`
The reason is that the parser expects this line to have only 3 entries after splitting at whitespaces. In fact I have previously never encountered a `0.0000` occupation entry for the LUMO.

I implemented and pushed a fix for this issue.
